#ifndef PTC_COMMON_PROTOCOL_CAPABILITY_BACKEND_H
#define PTC_COMMON_PROTOCOL_CAPABILITY_BACKEND_H

#define PTC_PLAY_TIMER_WRITE_BACKEND "pctl-s-v2"
#define PTC_PLAY_TIMER_EFFECT_BACKEND "pctl-s-runtime-v2"

#endif
