#ifndef PTC_ERROR_CODE_H
#define PTC_ERROR_CODE_H

typedef enum {
    PTC_ERR_OK = 0,

    PTC_ERR_UNSUPPORTED_VERSION = 100,
    PTC_ERR_BAD_REQUEST = 101,
    PTC_ERR_UNKNOWN_REQUEST_TYPE = 102,
    PTC_ERR_REQUEST_EXPIRED = 103,

    PTC_ERR_BAD_CODE = 200,
    PTC_ERR_BAD_TOKEN_VERSION = 201,
    PTC_ERR_UNSUPPORTED_TOKEN_ACTION = 202,
    PTC_ERR_BAD_SIGNATURE = 203,
    PTC_ERR_BAD_CLOCK = 204,
    PTC_ERR_WRONG_DATE = 205,
    PTC_ERR_USED_TOKEN = 206,
    PTC_ERR_MINUTES_EXCEED_LIMIT = 207,
    PTC_ERR_CODE_COOLDOWN = 208,

    PTC_ERR_DISABLED = 300,
    PTC_ERR_UNLIMITED_NOT_ALLOWED = 301,
    PTC_ERR_RAW_BLOCK_NOT_VERIFIED = 302,
    PTC_ERR_SUSPEND_NOT_VERIFIED = 303,
    PTC_ERR_PCTL_WRITE_NOT_VERIFIED = 304,
    PTC_ERR_PCTL_EFFECT_NOT_VERIFIED = 305,
    PTC_ERR_PCTL_EFFECT_NOT_OBSERVED = 306,
    PTC_ERR_PCTL_RESTORE_FAILED = 307,
    PTC_ERR_SETUP_PENDING = 308,
    PTC_ERR_RECOVERY_UNAVAILABLE = 309,
    PTC_ERR_RECOVERY_FAILED = 310,

    PTC_ERR_PCTL_INIT_FAILED = 400,
    PTC_ERR_PCTL_READ_FAILED = 401,
    PTC_ERR_PCTL_WRITE_FAILED = 402,
    PTC_ERR_PCTL_BACKUP_FAILED = 403,

    PTC_ERR_STORAGE_READ_FAILED = 500,
    PTC_ERR_STORAGE_WRITE_FAILED = 501,
    PTC_ERR_CONFIG_INVALID = 502,
    PTC_ERR_RULES_INVALID = 503
} PtcErrorCode;

const char *ptc_error_reason(PtcErrorCode code);
const char *ptc_error_message_zh(PtcErrorCode code);

#endif

