#ifndef PTC_IPC_PROTOCOL_H
#define PTC_IPC_PROTOCOL_H

#include <stdint.h>

#define PTC_IPC_SERVICE_NAME "pctc:u"
#define PTC_IPC_INTERFACE_VERSION 1u
#define PTC_IPC_MAX_REQUEST_SIZE 4096u
#define PTC_IPC_MAX_RESULT_SIZE 8192u
#define PTC_IPC_MAX_WAITERS 16u
#define PTC_IPC_RESULT_CACHE_SIZE 8u

typedef enum {
    PTC_IPC_CMD_GET_VERSION = 0,
    PTC_IPC_CMD_SUBMIT_REQUEST = 1,
    PTC_IPC_CMD_GET_RESULT = 2,
    PTC_IPC_CMD_NOTIFY_STORAGE_CHANGED = 3,
} PtcIpcCommand;

typedef enum {
    PTC_IPC_SUBMIT_ACCEPTED = 0,
    PTC_IPC_SUBMIT_DUPLICATE = 1,
    PTC_IPC_SUBMIT_CONFLICT = 2,
    PTC_IPC_SUBMIT_INVALID = 3,
    PTC_IPC_SUBMIT_STORAGE_FAILED = 4,
    PTC_IPC_SUBMIT_TOO_MANY_WAITERS = 5,
} PtcIpcSubmitStatus;

typedef enum {
    PTC_IPC_RESULT_READY = 0,
    PTC_IPC_RESULT_PENDING = 1,
    PTC_IPC_RESULT_NOT_FOUND = 2,
    PTC_IPC_RESULT_NOT_PERSISTED = 3,
    PTC_IPC_RESULT_BUFFER_TOO_SMALL = 4,
} PtcIpcResultStatus;

#endif
