#ifndef PTC_REQUEST_TYPE_H
#define PTC_REQUEST_TYPE_H

typedef enum {
    PTC_REQUEST_UNKNOWN = 0,
    PTC_REQUEST_OFFLINE_CODE = 1,
    PTC_REQUEST_STATUS = 2,
    PTC_REQUEST_SET_TODAY_LIMIT = 3,
    PTC_REQUEST_ADD_TODAY_MINUTES = 4,
    PTC_REQUEST_DISABLE_TODAY_LIMIT = 5,
    PTC_REQUEST_BLOCK_TODAY = 6,
    PTC_REQUEST_RESTORE_TODAY_POLICY = 7,
    PTC_REQUEST_SET_WEEKLY_TEMPLATE = 8,
    PTC_REQUEST_SET_BEDTIME = 9,
    PTC_REQUEST_SET_LIMIT_ACTION = 10,
    PTC_REQUEST_PARENT_UNLOCK_START = 11,
    PTC_REQUEST_PARENT_UNLOCK_END = 12,
    PTC_REQUEST_PROBE_RAW_BLOCK = 13,
    PTC_REQUEST_PROBE_SUSPEND = 14,
    PTC_REQUEST_PROBE_PLAY_TIMER_WRITE = 15
} PtcRequestType;

PtcRequestType ptc_request_type_from_string(const char *value);
const char *ptc_request_type_name(PtcRequestType type);

#endif

