#ifndef PTC_REQUEST_TYPE_H
#define PTC_REQUEST_TYPE_H

typedef enum {
    PTC_REQUEST_UNKNOWN = 0,
    PTC_REQUEST_OFFLINE_CODE = 1,
    PTC_REQUEST_STATUS = 2,
    PTC_REQUEST_SET_TODAY_LIMIT = 3,
    PTC_REQUEST_ADD_TODAY_MINUTES = 4,
    PTC_REQUEST_DISABLE_TODAY_LIMIT = 5,
    PTC_REQUEST_REMOVED_6 = 6,
    PTC_REQUEST_RESTORE_TODAY_POLICY = 7,
    PTC_REQUEST_SET_WEEKLY_TEMPLATE = 8,
    PTC_REQUEST_REMOVED_9 = 9,
    PTC_REQUEST_REMOVED_10 = 10,
    PTC_REQUEST_REMOVED_11 = 11,
    PTC_REQUEST_REMOVED_12 = 12,
    PTC_REQUEST_REMOVED_13 = 13,
    PTC_REQUEST_REMOVED_14 = 14,
    PTC_REQUEST_REMOVED_15 = 15,
    PTC_REQUEST_REMOVED_16 = 16,
    PTC_REQUEST_REMOVED_17 = 17,
    PTC_REQUEST_REMOVED_18 = 18,
    PTC_REQUEST_COMPLETE_SETUP = 19,
    PTC_REQUEST_RETRY_SETUP_RELEASE = 20,
    PTC_REQUEST_RESTORE_INSTALL_SNAPSHOT = 21,
    PTC_REQUEST_PREVIEW_OFFLINE_CODE = 22,
    PTC_REQUEST_SET_HOLIDAY_POLICY = 23
} PtcRequestType;

PtcRequestType ptc_request_type_from_string(const char *value);
const char *ptc_request_type_name(PtcRequestType type);

#endif

